FROM tv2dk/jetty-runtime:9.3
MAINTAINER playbackend@tv2.dk

ADD http://editor:KeyYDLJRCWmuQcge@a.artifactory.dev.tv2net.dk:8081/artifactory/libs-release-local/dk/tv2/play/ovp/play-ovp-conf-poc/0.1.0-release/play-ovp-conf-poc-0.1.0-release.war /webapps
